version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"
    labels:
      - "dependencies"
    assignees:
      - "giaoNguyen70"
